post_install() {
	cd tmp/pac4cli

	make install

	rm -fr tmp/pac4cli
}

post_upgrade() {
	cd tmp/pac4cli

	IS_ENABLED=$(systemctl is-enabled pac4cli 2>/dev/null)
	IS_ACTIVE=$(systemctl is-active pac4cli 2>/dev/null)

	make install

	if [[ "x$IS_ENABLED" == "enabled" ]]; then
		systemctl enable pac4cli
	fi
	if [[ "x$IS_ENABLED" != "x" && "x$IS_ACTIVE" == "active" ]]; then
		systemctl start pac4cli
	fi

	rm -fr tmp/pac4cli
}

post_remove() {
	opt/pac4cli/uninstall.sh
    rm -rf opt/pac4cli
}
